### ISSUE TITLE
Mobile navigation has no use

### ISSUE THREAD

**Issue by Sereri** [CephalofairGames/frosthaven-faq#12]
Currently when on mobile, there is a hamburger menu button on the top right that does very little besides expanding its box when pressed.

I would like it to either show a fly-out with the table of contents, or for it to be removed

![Screenshot_20240801-112532.png](https://github.com/user-attachments/assets/0c443f88-8963-432b-80c3-386cbd3bb96b)

**Comment by dwarf74** [comment]
Very fair, but I don't know how to do either here. :)

I didn't even expect there to be a hamburger button. 

I'll look into it though!

**Comment by bartaz** [comment]
It seems to be part of the minima theme. Seems like it thinks there are other pages to show in the menu, but there aren't any. I'm not sure if it's a bug in the theme, or something unusual with the setup of this repository.

**Comment by bartaz** [comment]
Done a bit of digging and it seems that it is (was) a bug in minima that was fixed long time ago: https://github.com/jekyll/minima/pull/289 but for some reason is not part of latest release yet. Overall, seems like minima hasn't been released officially in years, so I guess GH pages use the 2.5.1 version which still has this bug.

The version v3 has to be specifically installed it seems.

As a workaround the header part of the template can be overridden (using the new version from minima v3). I'll try to propose a PR later.

**Comment by dwarf74** [comment]
> As a workaround the header part of the template can be overridden (using the new version from minima v3). I'll try to propose a PR later.

Thanks! I started learning github less than two weeks ago, and appreciate any help.

**Comment by dwarf74** [comment]
Thank you!

Appreciate the help :)

**Comment by dwarf74** [comment]
> Done a bit of digging and it seems that it is (was) a bug in minima that was fixed long time ago: https://github.com/jekyll/minima/pull/289 but for some reason is not part of latest release yet. Overall, seems like minima hasn't been released officially in years, so I guess GH pages use the 2.5.1 version which still has this bug.
> 
> The version v3 has to be specifically installed it seems.
> 
> As a workaround the header part of the template can be overridden (using the new version from minima v3). I'll try to propose a PR later.

Mind if I thank you in the faq or Readme? You've been a great help.

**Comment by bartaz** [comment]
> Mind if I thank you in the faq or Readme? You've been a great help.

Seems like my contributions were quite trivial in comparison to all the work you are putting into this, so I would definitely be quite honoured and don't mind at all. Thanks!

**Comment by dwarf74** [comment]
> > Mind if I thank you in the faq or Readme? You've been a great help.
> 
> Seems like my contributions were quite trivial in comparison to all the work you are putting into this, so I would definitely be quite honoured and don't mind at all. Thanks!
> 
> 

Done, in the readme. Thanks again!
